global:
  app_name: "demo-api"
  env: "${ENVIRONMENT}"
  namespace: "example-co"
  image:
    repository: "123456789.dkr.ecr.eu-central-1.amazonaws.com"
    image_name: "demo-api-k8s-repo"
    tag: "${IMAGE_TAG}"
  resources:
    cpu_request: "500m"
    cpu_limit: "1000m"
    memory_request: "2G"
    memory_limit: "3G"
  ports:
    port: "3000"
    targetport: "3000"
  ingress:
    host: "${INGRESS_HOST}"
    path: /demo-api/(/|$)(.*)
    pathType: Prefix

applicationVariables:
  - name: AWS_ACCESS_KEY_ID
    value: "${AWS_ACCESS_KEY_ID}"
  - name: AWS_SECRET_ACCESS_KEY
    value: "${AWS_SECRET_ACCESS_KEY}"
  - name: POSTGRES_DB
    value: "${DB_NAME}"
  - name: POSTGRES_USER
    value: "${DB_USER}"
  - name: POSTGRES_PASSWORD
    value: "${DB_PASSWORD}"
  - name: POSTGRES_URL
    value: "${DB_HOST}"
  - name: POSTGRES_PORT
    value: "${DB_PORT}"
  - name: PORT
    value: "3000"
  - name: SERVER_TOKEN
    value: "${SERVER_TOKEN}"
