apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "{{ .Values.global.namespace }}"
  name: "{{ .Values.global.app_name }}"
  labels:
    app: '{{ .Values.global.app_name }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: '{{ .Values.global.app_name }}'
  template:
    metadata:
      labels:
        app: '{{ .Values.global.app_name }}'
    spec:
      containers:
        - name: '{{ .Values.global.app_name }}'
          image: '{{ .Values.global.image.repository }}/{{ .Values.global.image.image_name }}:{{ .Values.global.image.tag }}'
          imagePullPolicy: Always
          env:
            {{ toYaml .Values.applicationVariables | nindent 12 }}
          resources:
            requests:
              cpu: "{{ .Values.global.resources.cpu_request }}"
              memory: "{{ .Values.global.resources.memory_request }}"
            limits:
              cpu: "{{ .Values.global.resources.cpu_limit }}"
              memory: "{{ .Values.global.resources.memory_limit }}"
          ports:
            - containerPort: {{ .Values.global.ports.targetport }}
              name: nodejsport
              protocol: 'TCP'
