apiVersion: v1
kind: Service
metadata:
  namespace: "{{ .Values.global.namespace }}"
  name: "{{ .Values.global.app_name }}-service"
spec:
  selector:
    app: "{{ .Values.global.app_name }}"
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.global.ports.port }}
      targetPort: {{ .Values.global.ports.targetport }}
      name: "{{ .Values.global.app_name }}"
